"EXPRESSION : FORMULA ( @ | compare FORMULA )\n"
"FORMULA    : ( @ | plusminus ) TERM ( plusminus TERM )*\n"
"TERM       : FACTOR ( @ | starslash FACTOR )*\n"
"FACTOR     : ( IMMEDIATE | VARIABLE | lparen EXPRESSION rparen )\n"
"IMMEDIATE  : number\n"
"VARIABLE   : identifier\n"
