"STATEMENT                  : ( auto | EXPRESSION_STATEMENT | static )" "\n"
"EXPRESSION_STATEMENT       : ( @ | EXPRESSION ) semicolon" "\n"
"EXPRESSION                 : ASSIGNMENT_EXPRESSION ( comma ASSIGNMENT_EXPRESSION ) *" "\n"
"ASSIGNMENT_EXPRESSION      : CONSTANT" "\n"
"CONSTANT                   : ( integer_constant | character_constant | floating_constant | enumeration_constant )" "\n"
