"skip               : ( )( )*"                     "\n"
"term_operator      : (+|-)"                       "\n"
"factor_operator    : (\\*|/|%)"                   "\n"
"compare_operator   : (==|!=|>|>=|<|<=)"           "\n"
"equal              : ="                           "\n"
"comma              : ,"                           "\n"
"semicolon          : ;"                           "\n"
"lparen             : \\("                         "\n"
"rparen             : \\)"                         "\n"
"lbracket           : {"                           "\n"
"rbracket           : }"                           "\n"
"if_keyword         : if"                          "\n"
"else_keyword       : else"                        "\n"
"while_keyword      : while"                       "\n"
"return_keyword     : return"                      "\n"
"type_keyword       : int"                         "\n"
"identify           : (\\l|\\u|_)(\\l|\\u|_|\\d)*" "\n"
"number             : (0|(1|2|3|4|5|6|7|8|9)\\d*)" "\n"

